### ISSUE TITLE
user-can-turn-their-car

### ISSUE THREAD

**Issue by alvarodiazjr** [alvarodiazjr/driving-game#2]
## 💰 Motivation

The user needs to be able to control which way their car is facing.

## 📐 Plan

Rotate the image with CSS classes when the user presses an arrow key.

## ✅ Task List

- [x] Create a simple data model that includes what way the car is facing.
- [x] Listen for a 'keydown' event on the window.
- [x] Have the car rotate when the user presses an arrow key.
- [x] Check for errors or unnecessary CSS
