### ISSUE TITLE
user-can-start-their-car

### ISSUE THREAD

**Issue by alvarodiazjr** [alvarodiazjr/driving-game#3]
## 💰 Motivation

It's a driving game, duh!

## 📐 Plan

Move the car a few pixels every 16 milliseconds when the user presses space.

## ✅ Task List

- [x] Add cars location to data model.
- [x] Use absolute positioning for your car.
- [x] Change car's Top and Left box offset styles.
- [ ] Make movement smooth by moving car every 16 milliseconds.
- [ ] Check for errors or unnecessary styling.
